## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [6]:
import numpy as np
# print(dir(np))


In [12]:
arrObject = np.zeros(5)         #create a numpy array of 5 zeros. check datatype, itemsize and shape of above
print(arrObject)
print(arrObject.dtype)
print(arrObject.itemsize)
print(arrObject.shape)

[0. 0. 0. 0. 0.]
float64
8
(5,)


In [14]:
arrObject = np.ones((5,4))   #create a numpy array of ones of shape (5,4)
print(arrObject)
print(arrObject.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(5, 4)


In [22]:
arrObject = np.arange(1, 21)                 # for range 1 to 20 reshape is unable to make it so i have taken 21
arrShape = arrObject.reshape(4,5)
print(arrShape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [23]:
arrResult = arrShape * 10      #multiply all elements of above array by 10
print(arrResult)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [27]:
# print(arrObject)
oddNumber = np.arange(1,21,2)    #print odd elements from array
print(oddNumber)

[ 1  3  5  7  9 11 13 15 17 19]


In [56]:
number = np.arange(1,21)    #replace all even elements by their negative
result = number[number%2==0]
# print(result)
result = result * -1
print(result)

[ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]


In [60]:
M1 = np.arange(1, 17)                 # cannot reshape array of size 15 into shape (4,4) if you take arange(1,16)
arrShape = M1.reshape(4,4)            #create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
print(arrShape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [79]:
M1 = np.arange(1,17)
arrShape = M1.reshape(4,4)            #create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
# print(arrShape)
M2 = [[arrShape[j][i] for j in range(len(arrShape))] for i in range(len(arrShape[0]))]
# print(M2,'\n')
for r in M2:
    print(r)

[1, 5, 9, 13]
[2, 6, 10, 14]
[3, 7, 11, 15]
[4, 8, 12, 16]


In [85]:
# find sum of above matrix M3 = (M1 + M2)
M3 = (arrShape + r)
print(M3)


[[ 5 10 15 20]
 [ 9 14 19 24]
 [13 18 23 28]
 [17 22 27 32]]


In [87]:
#Find Transpose of M3, Call it MT1. Check if M3 == MT1
M3 = (arrShape + r)
MT1 = M3.transpose()
print(MT1)
print(M3 == MT1)

[[ 5  9 13 17]
 [10 14 18 22]
 [15 19 23 27]
 [20 24 28 32]]
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


In [89]:
#find diffrence of M4 = (M1 - M2)
M4 = (arrShape - r)                              #in above M1 is arrShape M1 = np.arange(1, 17)   after this line 
                                                  #arrShape = M1.reshape(4,4)     and r is M2 in above
print(M4)

[[ -3  -6  -9 -12]
 [  1  -2  -5  -8]
 [  5   2  -1  -4]
 [  9   6   3   0]]


In [93]:
#Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
M4 = (arrShape - r)
# print(M4)
MT2 = M4.transpose()
print(M4 == MT2)
print(M4 == -MT2)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False  True]]


In [102]:
#create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40, size=(3,4))
print(R1)
print('\n')
#find min and max column wise
print(np.amin(R1, axis=0))
print('\n')
print(np.amax(R1, axis=0))

[[25 38 15 36]
 [34 32 16 29]
 [19 13 20 10]]


[19 13 15 10]


[34 38 20 36]


In [114]:
#replace the last column with sum of all the columns
sumR1 = R1.sum()
print(sumR1)
R1[:,3] = sumR1
print(R1)

1104
[[  23   25   38 1104]
 [  23   13   14 1104]
 [  21   27   29 1104]]


In [124]:
# create a matrix (3x4) R1 of random numbers between 10-40
# replace all even elements with nan in R1
# count number of nan in R1
R1 = R1.astype('float')
R1[R1 % 2 == 0] = np.nan
print(R1)

[[23. 25. nan nan]
 [23. 13. nan nan]
 [21. 27. 29. nan]]


In [125]:
# check output of this code
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
