In [ ]:
# NUMPY
# create a numpy array of 5 zeros.
# check datatype, itemsize and shape of above
# create a numpy array of ones of shape (5,4)
# create a matrix of shape 4,5 with numbers from 1-20
# multiply all elements of above array by 10
# print odd elements from array
# replace all even elements by their negative

# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
# create a transpose of above matrix call it M2
# find sum of above matrix M3 = (M1 + M2)
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
# find diffrence of M4 = (M1 - M2)
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
# create a matrix (3x4) R1 of random numbers between 10-40
# find min and max column wise
# replace the last column with sum of all the columns
# create a matrix (3x4) R1 of random numbers between 10-40
# replace all even elements with nan in R1
# count number of nan in R1
# check output of this code
# a1 = np.arange(1,10).reshape(3,3)
# a2 = np.arange(11,20).reshape(3,3)
# a3 = np.append(a1,a2)
# print(a3)
# a3 = np.append(a1,a2, axis = 0)
# print(a3)
# a3 = np.append(a1,a2, axis = 1)
# print(a3)

In [4]:
# create a numpy array of 5 zeros.
# check datatype, itemsize and shape of above
import numpy as np

arr = np.zeros(5)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.itemsize)

[0. 0. 0. 0. 0.]
float64
(5,)
8


In [6]:
# create a numpy array of ones of shape (5,4)
arr_ones = np.ones((5,4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
# create a matrix of shape 4,5 with numbers from 1-20
matrix = np.arange(1,21).reshape(4,5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [9]:
# multiply all elements of above array by 10
mul_matrix = matrix * 10
print(mul_matrix)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [12]:
#print odd elements from array
print(matrix[matrix % 2 != 0])

[ 1  3  5  7  9 11 13 15 17 19]


In [25]:
# replace all even elements by their negative
even_matrix = np.where(matrix % 2 == 0, -1 * matrix, matrix)
print(even_matrix)

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [26]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
M1 = np.arange(1,17).reshape(4,4)
print(M1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [27]:
# create a transpose of above matrix call it M2
M2 = M1.T
print(M2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [28]:
# find sum of above matrix M3 = (M1 + M2)
M3 = M1 + M2
print(M3)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [30]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = M3.T
print((M3 == MT1).all())

True


In [31]:
# find diffrence of M4 = (M1 - M2)
M4 = M1 - M2
print(M4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [33]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 = M4.T
print((M4 == MT2).all())
print((M4 == -MT2).all())

False
True


In [38]:
# create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,size = (3,4))
print(R1)

[[29 28 30 38]
 [30 33 35 23]
 [37 31 13 11]]


In [40]:
# find min and max column wise
min_col = R1.min(axis = 0)
max_col = R1.max(axis = 0)
print(min_col)
print(max_col)

[29 28 13 11]
[37 33 35 38]


In [57]:
# replace the last column with sum of all the columns
R1[:,3] = R1.sum()
print(R1)

[[       29       338        30 399446208]
 [       30       338        35 399446208]
 [       37       338        13 399446208]]


In [58]:
# create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,size = (3,4))
print(R1)

[[19 34 11 25]
 [16 17 16 28]
 [23 26 31 39]]


In [59]:
# replace all even elements with nan in R1
R1 = np.where(R1%2 == 0, np.nan, R1)
print(R1)

[[19. nan 11. 25.]
 [nan 17. nan nan]
 [23. nan 31. 39.]]


In [ ]:
# count number of nan in R1
np_count = np.

In [65]:
# check output of this code
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a1)
print(a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
