In [2]:
import numpy as np

In [136]:
# create a numpy array of 5 zeros

a = np.zeros(5)
print('a:',a)
print(f'dtype: {a.dtype}')
print(f'itemsize: {a.itemsize}')
print(f'shape: {a.shape}')

a: [0. 0. 0. 0. 0.]
dtype: float64
itemsize: 8
shape: (5,)


In [134]:
# create a numpy array of ones of shape (5,4)

a = np.ones((5,4), dtype='int32')
print('a:',a,sep='\n')

a:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [141]:
# create a matrix of shape 4,5 with numbers from 1-20

a = np.arange(1,21).reshape(4,5)
print('a:',a,sep='\n')

# multiply all elements of above array by 10
print()
print('Multiplying all elements by 10:',a*10,sep='\n')

# print odd elements from array
print()
print('Odd elements:',a[a % 2 != 0])

# replace all even elements by their negative
print()
a[a%2==0] *= -1
print('a after replacing all even elements by their negative:',a,sep='\n')

a:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Multiplying all elements by 10:
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]

Odd elements: [ 1  3  5  7  9 11 13 15 17 19]

a after replacing all even elements by their negative:
[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [85]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

M1 = np.arange(1,17).reshape((4,4))
print('M1:',M1,sep='\n')

M1:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [86]:
# create a transpose of above matrix call it M2

M2 = M1.T
print('M2(Transpose of M1):',M2,sep='\n')

M2(Transpose of M1):
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [87]:
# find sum of above matrix M3 = (M1 + M2)

M3 = M1 + M2     # M3 = np.add(M1,M2) is an alternative
print('M3(M1+M2):',M3,sep='\n')

M3(M1+M2):
[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [88]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1

MT1 = M3.T
print('MT1(Transpose of M3):',MT1,sep='\n')
print('If M3 == MT1:',np.array_equal(M3,MT1))

MT1(Transpose of M3):
[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]
If M3 == MT1: True


In [89]:
# find diffrence of M4 = (M1 - M2)

M4 = M1 - M2
print('M4(M1-M2):',M4,sep='\n')

M4(M1-M2):
[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [90]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

MT2 = M4.T
print('MT2(Transpose of M4):',MT2,sep='\n')
print('If M4 == MT2:',np.array_equal(M4,MT2))
print('If M4 == -MT2:',np.array_equal(M4,-MT2))

MT2(Transpose of M4):
[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]
If M4 == MT2: False
If M4 == -MT2: True


In [91]:
# create a matrix (3x4) R1 of random numbers between 10-40

R1 = np.random.randint(10,40,(3,4))
print('R1:',R1,sep='\n')

R1:
[[32 22 21 18]
 [11 31 22 19]
 [21 11 20 32]]


In [92]:
# find min and max column wise

print('Min value column wise:',np.amax(R1, axis=0))
print('Max value column wise:',np.amin(R1, axis=0))

Min value column wise: [32 31 22 32]
Max value column wise: [11 11 20 18]


In [93]:
# replace the last column with sum of all the columns

R1[:,3] = np.sum(R1, axis=1)
print('R1 after replacing last column with sum of all columns:',R1,sep='\n')

R1 after replacing last column with sum of all columns:
[[32 22 21 93]
 [11 31 22 83]
 [21 11 20 84]]


In [110]:
# create a matrix (3x4) R1 of random numbers between 10-40

R1 = np.random.randint(10,40,(3,4))
print('R1:',R1,sep='\n')

R1:
[[18 18 35 31]
 [15 22 37 28]
 [23 11 35 27]]


In [111]:
# replace all even elements with nan in R1

R1 = R1.astype('float')
R1[R1 % 2==0] = np.nan
print('R1 after replacing all even elements with nan:',R1,sep='\n')

R1 after replacing all even elements with nan:
[[nan nan 35. 31.]
 [15. nan 37. nan]
 [23. 11. 35. 27.]]


In [123]:
# count number of nan in R1

print('Count of nan in R1:',np.count_nonzero(np.isnan(R1)))

Count of nan in R1: 4


In [129]:
# check output of this code

a1 = np.arange(1,10).reshape(3,3)
print('a1:',a1,sep='\n')

a2 = np.arange(11,20).reshape(3,3)
print('a2:',a2,sep='\n')

a3 = np.append(a1,a2)
print('a3 with no axis argument:',a3,sep='\n')

a3 = np.append(a1,a2, axis = 0)
print('a3 with axis=0:',a3,sep='\n')

a3 = np.append(a1,a2, axis = 1)
print('a3 with axis=1:',a3,sep='\n')

a1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
a2:
[[11 12 13]
 [14 15 16]
 [17 18 19]]
a3 with no axis argument:
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
a3 with axis=0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
a3 with axis=1:
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
