In [8]:
#1
a = []
a = [1]

#2
t = ()
t = (1, 'abcd')
print(a, t)

[1] (1, 'abcd')


In [5]:
#1
a = [10,20]
a[0] = 100
print(a)

#2
a = (10,20)
a[0] = 100
print(a)

[100, 20]


TypeError: 'tuple' object does not support item assignment

In [ ]:
a = [10,20,True , 'abcd']
# array : there can be multiple elements like a python list, but each thing has same data type

In [ ]:
a1 = [10 ,20 , 30 ,40]
a2 =  [1,  2 ,  3,  4] * 1000000

In [9]:
import numpy as np

In [12]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

0

In [20]:
x = 10000000000000000
np.int64(x)

10000000000000000

In [31]:
a = np.array((1,2))
print(a, type(a))
print(a.dtype)
print(a.shape)
print(a.itemsize)
print(a.size)
print(a.T, type(a.T))
print(a.T.shape)

[1 2] <class 'numpy.ndarray'>
int32
(2,)
4
2
[1 2] <class 'numpy.ndarray'>
(2,)


In [41]:
a = np.array([1 ,2 ,3 ], dtype = np.int8)
print(a.dtype)

print()
a = np.array([1 ,2 ,300000 ], dtype = np.int8)
print(a.dtype, a)

print()
a = np.array([1 ,2 ,300000 ], dtype = 'int64')
print(a.dtype, a)

print()
a = np.array([1 ,2.0 ,300000 ])
print(a.dtype, a)

int8

int8 [  1   2 -32]

int64 [     1      2 300000]

float64 [1.e+00 2.e+00 3.e+05]


In [54]:
a = np.arange(10)
print(a)

print()
a = np.arange(10,20)
print(a)

print()
a = np.arange(10,20, 2)
print(a, a.dtype)

[0 1 2 3 4 5 6 7 8 9]

[10 11 12 13 14 15 16 17 18 19]

[10 12 14 16 18] int32


In [53]:
a = np.ones(10, dtype='int8')
print(a)

print()
a = np.ones((3, 2))
print(a, a.dtype)


print()
a = np.ones((4, 3, 2))
print(a)

print()
a = np.zeros(4)
print(a)


[1 1 1 1 1 1 1 1 1 1]

[[1. 1.]
 [1. 1.]
 [1. 1.]] float64

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]

[0. 0. 0. 0.]


In [72]:
a = np.linspace(10, 20, 101) # logspace()
print(a)

[10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1 11.2 11.3
 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5 12.6 12.7
 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9 14.  14.1
 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3 15.4 15.5
 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9
 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1 18.2 18.3
 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5 19.6 19.7
 19.8 19.9 20. ]


In [89]:
x = np.random.randint(10)
print(x)

print()
x = np.random.randint(10, 20)
print(x)


print()
x = np.random.randint(10, 20, 100)
print(x)

print(dir(np.random))

print()
print(np.random.randn(2,3))

6

18

[11 11 16 15 12 10 16 18 18 12 17 16 16 16 12 10 12 10 17 15 19 18 13 14
 17 18 18 16 19 12 19 13 12 19 17 10 11 19 17 16 10 13 16 10 14 13 13 16
 19 13 13 10 12 19 12 14 18 18 15 13 11 15 10 13 13 16 12 19 14 18 14 12
 13 17 18 18 18 16 15 19 11 14 17 15 14 15 11 16 16 13 17 11 11 11 16 16
 10 13 16 19]
['Lock', 'RandomState', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'division', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'np', 'operator', 'pareto', 'permutation', 'poisson', 'power', 'print_function', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'r

In [90]:
a = np.arange(1,13)
print(a)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [93]:
a = np.arange(1,13)
print(a)
print(a.shape)

print()
r = a.reshape(3,4)
print(r, r.shape)
print(a)

print()
r = a.reshape(3,3) # this gives error since total elements are 4
print(r, r.shape)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12]



ValueError: cannot reshape array of size 12 into shape (3,3)

In [98]:
a = np.arange(1,13)
print(a)
print(a.shape)

print()
a.resize(3,4)
print(a)

print()
r = a.resize(3,3)
print(r)
print(a)

print()
r = a.resize(3,3,3)
print(r)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

None
[[1 2 3]
 [4 5 6]
 [7 8 9]]

None
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [100]:
a = [10,20]
print(a + 10)

TypeError: can only concatenate list (not "int") to list

In [107]:
a = np.arange(-10,10).reshape(4,5)
print(a)

print(a + 10)
print(a * 10)

print()
print(a)
a = a ** 2
print(a)

[[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[-100  -90  -80  -70  -60]
 [ -50  -40  -30  -20  -10]
 [   0   10   20   30   40]
 [  50   60   70   80   90]]

[[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]
[[100  81  64  49  36]
 [ 25  16   9   4   1]
 [  0   1   4   9  16]
 [ 25  36  49  64  81]]


In [114]:
a = np.arange(-10,10).reshape(4,5)
print(a)

print(a > 5)

print()
print(a % 2 == 0)

print()
print((a > -5) & (a < 5))

print()
print((a % 3==0) | (a %5 ==0 ))

[[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False  True  True  True  True]]

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]

[[False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False False]]

[[ True  True False False  True]
 [ True False  True False False]
 [ True False False  True False]
 [ True  True False False  True]]


In [119]:
a = [10,20,30,40]
print(type(a[0]))
print(type(a[0 : 0]), a[0 : 0])
print(type(a))
print(type(a[0 : 3]))

<class 'int'>
<class 'list'> []
<class 'list'>
<class 'list'>


In [123]:
a = np.arange(-10,10)
print(a)

print(a[0])
print(a[1:9:2])


[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]
-10
[-9 -7 -5 -3]


In [144]:
a = np.arange(-10,10).reshape(4,5)
print(a)

print()
print(a[0])


print()
print(a[:, 0])

print()
print(a[1:9:2])

print()
print(a[0][0])

[[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]

[-10  -9  -8  -7  -6]

[-10  -5   0   5]

[[-5 -4 -3 -2 -1]
 [ 5  6  7  8  9]]

-10


In [134]:
a = np.arange(-10,10).reshape(4,5)
print(a) # 2 dim

print()
print(a[1, 4]) # 0

print()
print(a[1:3 , 4]) # 1

print()
print(a[1 , 1:4]) # 1

print()
print(a[1:3 , 1:4]) # 2

[[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]

-1

[-1  4]

[-4 -3 -2]

[[-4 -3 -2]
 [ 1  2  3]]


In [142]:
a = np.arange(-10,10).reshape(4,5)
print(a) # 2 dim

print()
print(a[ [0,2] ])

print()
print(a[ :, [0,2] ])

print()
print(a[ [0,2] ,[2,3]])

[[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]

[[-10  -9  -8  -7  -6]
 [  0   1   2   3   4]]

[[-10  -8]
 [ -5  -3]
 [  0   2]
 [  5   7]]

[-8  3]


In [147]:
a = np.arange(-10,10).reshape(4,5)
print(a)

print()
i = a % 2 == 0
print(i)

print()
r = a[i]
print(r)



[[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]

[-10  -8  -6  -4  -2   0   2   4   6   8]


In [151]:
a = np.arange(-10,10).reshape(4,5)
print(a)

print()
print(a.sum())

print()
print(a.min())

print()
print(a.max())

[[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]

-10

-10

9


In [156]:
a = np.arange(-10,10).reshape(4,5)
print(a)

print()
print(a.min(axis=0))

print()
print(a.min(axis=1))

print()
print(a.min())

print()
print(a.mean(axis = 0))

[[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]

[-10  -9  -8  -7  -6]

[-10  -5   0   5]

-10

[-2.5 -1.5 -0.5  0.5  1.5]


In [159]:
a = np.arange(-10,10).reshape(4,5)
print(a)

r  = (a % 2 == 0)
print()
print(r)
print(r.sum())

[[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]
10
