In [8]:
# create a numpy array of 5 zeros.
# check datatype, itemsize and shape of above

import numpy as np
a = np.zeros(5)
print(a,a.dtype,a.shape)

[0. 0. 0. 0. 0.] float64 (5,)


In [11]:
# create a numpy array of ones of shape (5,4)

import numpy as np
a=np.ones((5,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [107]:
# create a matrix of shape 4,5 with numbers from 1-20
import numpy as np
a = np.arange(1,21)

print("# create a matrix of shape 4,5 with numbers from 1-20")
print(a.resize(4,5))
print()
# multiply all elements of above array by 10
print("# multiply all elements of above array by 10")
print(a*10)
print()
# print odd elements from array
print("# print odd elements from array")
i = a%2==1
print()
print("Replace all even elements by their negative")
j = a%2==0
print(a[j]*-1)


# create a matrix of shape 4,5 with numbers from 1-20
None

# multiply all elements of above array by 10
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]

# print odd elements from array

Replace all even elements by their negative
[ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]


In [97]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
import numpy as np
M1 = np.linspace(1,16,16)
M1.resize(4,4)
print(M1)
print()
print("create a transpose of above matrix call it M2")
M2= np.transpose(M1)
print(M2)
print()
print("find sum of above matrix M3 = (M1 + M2)")
M3 = M1+M2
print(M3)
print()
print("Find Transpose of M3, Call it MT1. Check if M3 == MT1")
MT1 = np.transpose(M3)
print(M3==MT1)
print()
print("find diffrence of M4 = (M1 - M2)")
M4 = M1-M2
print(M4)
print()
print(" Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2")
MT2=np.transpose(M4)
print(M4 == MT2)
print(M4 == (-MT2))

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

create a transpose of above matrix call it M2
[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]

find sum of above matrix M3 = (M1 + M2)
[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]

Find Transpose of M3, Call it MT1. Check if M3 == MT1
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

find diffrence of M4 = (M1 - M2)
[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]

 Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [85]:
#create a matrix (3x4) R1 of random numbers between 10-40
a = np.random.randint(10,40,size=(3,4))
print(a)
print()
#find min and max column wise
print("Min col wise :",a.min(axis=0))
print("Max col wise :",a.max(axis=0))
print("Min row wise :",a.min(axis=1))
print("Max row wise :",a.max(axis=1))
#replace the last column with sum of all the columns


[[13 36 12 32]
 [11 31 27 17]
 [22 35 27 29]]

Min col wise : [11 31 12 17]
Max col wise : [22 36 27 32]
Min row wise : [12 11 22]
Max row wise : [36 31 35]


In [113]:

# - create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,size=(3,4))
print(R1)
# - replace all even elements with nan in R1
i=R1%2==0
j=R1%2==1
R1[R1==NDV]=np.nan
# - count number of nan in R1


[[12 21 35 14]
 [23 36 32 30]
 [39 37 23 17]]


NameError: name 'NDV' is not defined

In [115]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
print("-------")
a3 = np.append(a1,a2, axis = 0)
print(a3)
print("-------")
a3 = np.append(a1,a2, axis = 1)
print(a3)
print("-------")

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
-------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
-------
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
-------
