In [4]:
#create a numpy array of 5 zeros.
#check datatype, itemsize and shape of above

import numpy as np
a = np.zeros(5)
print(a)

print(a.dtype)
print(a.itemsize)
print(a.shape)


[0. 0. 0. 0. 0.]
float64
8
(5,)


In [5]:
#create a numpy array of ones of shape (5,4)


import numpy as np

a = np.ones((5,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
#create a matrix of shape 4,5 with numbers from 1-20

import numpy as np

a = np.arange(1,21)
#print(a)

b = a.reshape(4,5)
print(b)
print()



#multiply all elements of above array by 10

print(b*10)
print()


#print odd elements from array

print(b[b%2!=0])
print()


#print(b)
#replace all even elements by their negative

c= np.where((b%2==0),-b,b)

print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]

[ 1  3  5  7  9 11 13 15 17 19]

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [36]:
#create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

import numpy as np

a = np.arange(1,17)
m1 = a.reshape(4,4)
print(m1)
print()

#create a transpose of above matrix call it M2

m2 = m1.T

print(m2)
print()


#find sum of above matrix M3 = (M1 + M2)

m3 = m1+m2
print(m3)
print()


#Find Transpose of M3, Call it MT1. Check if M3 == MT1

mt1 = m3.T
print(mt1)
print()


print(m3==mt1)
print()


#find diffrence of M4 = (M1 - M2)

m4 = m1-m2
print(m4)
print()

#Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

mt2 = m4.T
print(mt2)
print()


print(m4==mt2)
print()

print(m4==-mt2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [12]:
#create a matrix (3x4) R1 of random numbers between 10-40

import numpy as np

r = np.arange(10,40)

a = np.random.randint(10,40,12)
#print(a)
print()

r1 = a.reshape(3,4)
print(r1)
print()


#find min and max column wise

min = np.min(r1,axis =0)
print(min)
print()

max = np.max(r1,axis =0)
print(max)
print()



#replace the last column with sum of all the columns
#sum = np.sum(r1,axis=0)
#print(sum)

r1[:,3] = np.sum(r1,axis=1)

print(r1)





[[32 26 16 35]
 [10 39 16 11]
 [22 21 34 16]]

[10 21 16 11]

[32 39 34 35]

[[ 32  26  16 109]
 [ 10  39  16  76]
 [ 22  21  34  93]]


In [13]:
#create a matrix (3x4) R1 of random numbers between 10-40

import numpy as np

r = np.random.randint(10,40,12)
r1 = r.reshape(3,4)
print(r1)
print()


#replace all even elements with nan in R1
r2 = np.where((r1%2==0),np.nan,r1)
print(r2)
print()


#count number of nan in R1

count = np.count_nonzero(np.isnan(r2))

print(count)




[[32 35 36 29]
 [10 31 28 38]
 [26 38 25 32]]

[[nan 35. nan 29.]
 [nan 31. nan nan]
 [nan nan 25. nan]]

8


In [45]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
