In [2]:
import numpy as np
a = np.zeros((5), dtype=np.int16)
print(a)
print('Datatype of ndarray:',a.dtype)
print('shape of ndarray :', a.shape) 
print('Size of each items in ndarray :', a.itemsize) 

[0 0 0 0 0]
Datatype of ndarray: int16
shape of ndarray : (5,)
Size of each items in ndarray : 2


In [19]:
#•	create a numpy array of ones of shape (5,4)
a = np.ones((5,4), dtype=np.int16)
print(a)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [76]:
#•	create a matrix of shape 4,5 with numbers from 1-20
inp_list = np.arange(20).reshape(4,5) 
print(inp_list)

#•	multiply all elements of above array by 10
print('multiply all elements of above array by 10')
b=np.full((4,5), 10)
print(np.multiply(inp_list,b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
multiply all elements of above array by 10
[[  0  10  20  30  40]
 [ 50  60  70  80  90]
 [100 110 120 130 140]
 [150 160 170 180 190]]


In [58]:
#•	print odd elements from array
inp_list = np.arange(20)
print("Odd number from matrix(4,5)",inp_list[inp_list%2==1])

Odd number from matrix(4,5) [ 1  3  5  7  9 11 13 15 17 19]


In [87]:
#replace all even elements by their negative
inp_list = np.arange(20)
a = np.where(inp_list%2==0, inp_list * -1, inp_list)
print(a)

[  0   1  -2   3  -4   5  -6   7  -8   9 -10  11 -12  13 -14  15 -16  17
 -18  19]


In [89]:
#•	create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
a1 = np.arange(1,10).reshape(3,3) 
a2 = np.arange(11,20).reshape(3,3) 
a3 = np.append(a1,a2) 
print(a3) 
a3 = np.append(a1,a2, axis = 0) 
print(a3) 
a3 = np.append(a1,a2, axis = 1) 
print(a3)



[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [163]:
#•	create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
M1=np.linspace(1,16,16,dtype=np.int32).reshape(4,4)
print(M1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [164]:
#•	create a transpose of above matrix call it M2
M2 = M1[::-1]
print(M2)

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [165]:
#•	find sum of above matrix M3 = (M1 + M2)
M3= np.add(M1,M2)
print(M3)

[[14 16 18 20]
 [14 16 18 20]
 [14 16 18 20]
 [14 16 18 20]]


In [166]:
#•	Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1=M3[::-1]
print(MT1)
np.array_equiv(M3,MT1)

[[14 16 18 20]
 [14 16 18 20]
 [14 16 18 20]
 [14 16 18 20]]


True

In [167]:
#•	find diffrence of M4 = (M1 - M2)
M4=np.subtract(M1,M2)
print(M4)

[[-12 -12 -12 -12]
 [ -4  -4  -4  -4]
 [  4   4   4   4]
 [ 12  12  12  12]]


In [168]:
#•	Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2=M4[::-1]
print("M4 == MT2?\n",np.array_equiv(M4,MT2))

print("M4 == -MT2?\n",np.array_equiv(M4,MT2*-1))


M4 == MT2?
 False
M4 == -MT2?
 True


In [12]:
#•	create a matrix (3x4) R1 of random numbers between 10-40
x=np.random.randint(10,40,12).reshape(3,4)
print(x)

[[32 18 11 36]
 [26 15 19 19]
 [34 19 11 37]]


In [13]:
#•	find min and max column wise
min = np.amin(x, axis=0)
print('min value of every column: ', min)
max = np.amax(x, axis=0)
print('min value of every column: ', max)

min value of every column:  [26 15 11 19]
min value of every column:  [34 19 19 37]


In [14]:
#•	replace the last column with sum of all the columns
x[:,3] = np.sum(x, axis=1)
print(x)


[[ 32  18  11  97]
 [ 26  15  19  79]
 [ 34  19  11 101]]


In [15]:
#•	replace all even elements with nan in R1
a = np.where(x%2==0, np.nan, x)
print(a)

[[ nan  nan  11.  97.]
 [ nan  15.  19.  79.]
 [ nan  19.  11. 101.]]


In [18]:
a_count=np.isnan(a).sum()
print('number of nan in R1:',a_count)

number of nan in R1: 4
