## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [4]:
# create a numpy array of 5 zeros.
# check datatype, itemsize and shape of above

import numpy as np
arrayNew = np.zeros(5)                      # without defining Datatype
arrayNew1 = np.zeros(5, dtype='int32')      # With defined datatype int32


print(type(arrayNew))               # Type of array        
print(type(arrayNew1))              # Type of array

print(type(arrayNew[0]))            # Type of element of array
print(type(arrayNew1[0]))           # Type of element of array


print(arrayNew.itemsize)            # itemsize of float dtype array
print(arrayNew1.itemsize)           # itemsize of int32 dtype array

print(arrayNew.shape)               # shape of array = one dimensional 5 elements

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.int32'>
8
4
(5,)


In [18]:
#create a numpy array of ones of shape (5,4)
arrayNew = np.zeros(20, dtype='int32').reshape(5,4)
print(arrayNew)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [39]:
# create a matrix of shape 4,5 with numbers from 1-20
# multiply all elements of above array by 10
# print odd elements from array
# replace all even elements by their negative

arrayNew = np.arange(1,21).reshape(4,5)
print(arrayNew)        # array of 20 elements from of matrix (4,5)

print()
multArray = arrayNew*10
print(multArray)       # array of 20 elements multiplied by 10


print()
print(arrayNew[arrayNew % 2 != 0])     # All odd elements


print()
arrayNew = (arrayNew *-1)          # replaced all elements by their negative value
print(arrayNew)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]

[ 1  3  5  7  9 11 13 15 17 19]

[[ -1  -2  -3  -4  -5]
 [ -6  -7  -8  -9 -10]
 [-11 -12 -13 -14 -15]
 [-16 -17 -18 -19 -20]]


In [14]:
# - create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
# - create a transpose of above matrix call it M2
# - find sum of above matrix M3 = (M1 + M2)
# - Find Transpose of M3, Call it MT1. Check if M3 == MT1
# - find diffrence of M4 = (M1 - M2)
# - Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2


M1 = np.arange(1,17).reshape(4,4)          # M1 matrix of 4,4 with values 1-16
print(M1)   

print("\nTranspose of M1")
M2 = M1.T                                  # Transpose of Matrix M1
print(M2)


print("\nSum of M1 and M2")
M3 = np.add(M1,M2)                            # Sum Of Matrix M1 and M2
print(M3)


MT1 = M3.T                                   # Transpose of M3 as MT1 
print("\n Transpose of M3 is MT1")
print(MT1)

print("\n Checking if MT1 == M3\n",MT1 == M3)  #Checking if MT1 == M3


M4 = (M1 - M2)
print("\n M1 -M2 is \n",M4)      # M1 - M2

 
MT2 = M4.T                         # Transpose of M4 as MT2
print("\n Transpose of M4 \n", MT2)


# Check if M4 == MT2. Also check if M4 == -MT2
print("\nchecking if M4 == MT2\n",M4 == MT2)           # checking if M4 == MT

print("\nchecking if M4 == -MT22\n",M4 == -MT2)         # checking if M4 == -MT22


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose of M1
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Sum of M1 and M2
[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

 Transpose of M3 is MT1
[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

 Checking if MT1 == M3
 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

 M1 -M2 is 
 [[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]

 Transpose of M4 
 [[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]

checking if M4 == MT2
 [[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

checking if M4 == -MT22
 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [72]:
# create a matrix (3x4) R1 of random numbers between 10-40
# find min and max column wise
# replace the last column with sum of all the columns

R1 = np.random.randint(low=10, high=40, size=(12)).reshape(3,4)        #matrix of 12(3x4) elements, number between 10-40
print("matrix of 12(3x4) elements, number between 10-40\n\n",R1)

print("\n Minimum number of array\n",R1.min())

print("\n Maximum number of array\n",R1.max())

R1Sum = np.sum(R1, axis = 1)                # Sum of all columns of Matrix N1
print("\n Sum of all columns of Matrix N1\n", R1Sum)


print("\n Replaced last element with sum of N1 mtrix")
R1[:,3] = R1Sum                  #Replaced last element with sum of all columns of N1 matrix
print(R1)

matrix of 12(3x4) elements, number between 10-40

 [[37 37 14 35]
 [31 31 34 20]
 [34 19 21 37]]

 Minimum number of array
 14

 Maximum number of array
 37

 Sum of all columns of Matrix N1
 [123 116 111]

 Replaced last element with sum of N1 mtrix
[[ 37  37  14 123]
 [ 31  31  34 116]
 [ 34  19  21 111]]


In [104]:
# create a matrix (3x4) R1 of random numbers between 10-40
# replace all even elements with nan in R1
# count number of nan in R1

R1 = np.random.randint(low=10, high=40, size=(12)).reshape(3,4)        #matrix of 12(3x4) elements, number between 10-40
print("matrix of 12(3x4) elements, number between 10-40\n\n",R1)

R1 = R1.astype('float')
R1[R1 % 2==0] = np.nan                                         #Replaced all even numbers with nan
print("\nReplaced all even numbers with nan\n",R1)


print("\n Number of Nan in numpy array\n",np.count_nonzero(np.isnan(R1)))

matrix of 12(3x4) elements, number between 10-40

 [[23 30 29 38]
 [37 20 11 24]
 [18 11 38 20]]

Replaced all even numbers with nan
 [[23. nan 29. nan]
 [37. nan 11. nan]
 [nan 11. nan nan]]

 Number of Nan in numpy array
 7


In [106]:
# check output of this code

a1 = np.arange(1,10).reshape(3,3)
print(a1)
a2 = np.arange(11,20).reshape(3,3)
print(a2)
a3 = np.append(a1,a2)
print(a3)                         # if we dont mention axis in append function it will return data in only on dimension
a3 = np.append(a1,a2, axis = 0)
print(a3)                         # if we give axis as 0 than the append function will append data row/column wise appropriately
a3 = np.append(a1,a2, axis = 1)
print(a3)                         # if we give axis as 1 than the append function will append data column/row wise appropriately

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
