In [ ]:
## NUMPY
# - create a numpy array of 5 zeros.
#     - check datatype, itemsize and shape of above
# - create a numpy array of ones of shape (5,4)
# - create a matrix of shape 4,5 with numbers from 1-20
# - multiply all elements of above array by 10
# - print odd elements from array
# - replace all even elements by their negative
  
  
  
# - create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
# - create a transpose of above matrix call it M2
# - find sum of above matrix M3 = (M1 + M2)
# - Find Transpose of M3, Call it MT1. Check if M3 == MT1
# - find diffrence of M4 = (M1 - M2)
# - Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

# - create a matrix (3x4) R1 of random numbers between 10-40
# - find min and max column wise
# - replace the last column with sum of all the columns


# - create a matrix (3x4) R1 of random numbers between 10-40
# - replace all even elements with nan in R1
# - count number of nan in R1



# - check output of this code  
# `a1 = np.arange(1,10).reshape(3,3)
# a2 = np.arange(11,20).reshape(3,3)
# a3 = np.append(a1,a2)
# print(a3)
# a3 = np.append(a1,a2, axis = 0)
# print(a3)
# a3 = np.append(a1,a2, axis = 1)
# print(a3)




In [3]:
# - create a numpy array of 5 zeros.
#     - check datatype, itemsize and shape of above

import numpy as np
a=np.zeros(5)
print(a)
print(a.dtype)
print(a.itemsize)
print(a.shape)

[0. 0. 0. 0. 0.]
float64
8
(5,)


In [4]:
#- create a numpy array of ones of shape (5,4)

import numpy as np
a=np.ones((5,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
#- create a matrix of shape 4,5 with numbers from 1-20
import numpy as np
a=np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [6]:
#- multiply all elements of above array by 10
import numpy as np
a=np.arange(1,21).reshape(4,5)
print(a*10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [9]:
#- print odd elements from array
import numpy as np
a=np.arange(1,21).reshape(4,5)
print(a)
i=a%2!=0
print(a[i])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  3  5  7  9 11 13 15 17 19]


In [41]:
#- replace all even elements by their negative
import numpy as np
a=np.arange(1,21).reshape(4,5)
print(a)
i=a%2==0
a[i]=-1*a[i]
print(a)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [29]:
#- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

import numpy as np
m1=np.linspace(1,17,16).reshape(4,4)
print(m1)

[[ 1.          2.06666667  3.13333333  4.2       ]
 [ 5.26666667  6.33333333  7.4         8.46666667]
 [ 9.53333333 10.6        11.66666667 12.73333333]
 [13.8        14.86666667 15.93333333 17.        ]]


In [30]:
#- create a transpose of above matrix call it M2
import numpy as np
m1=np.linspace(1,17,16).reshape(4,4)
m2=m1.T
print(m2)

[[ 1.          5.26666667  9.53333333 13.8       ]
 [ 2.06666667  6.33333333 10.6        14.86666667]
 [ 3.13333333  7.4        11.66666667 15.93333333]
 [ 4.2         8.46666667 12.73333333 17.        ]]


In [31]:
#- find sum of above matrix M3 = (M1 + M2)
import numpy as np
m1=np.linspace(1,17,16).reshape(4,4)
m2=m1.T
m3=m1+m2
print(m3)

[[ 2.          7.33333333 12.66666667 18.        ]
 [ 7.33333333 12.66666667 18.         23.33333333]
 [12.66666667 18.         23.33333333 28.66666667]
 [18.         23.33333333 28.66666667 34.        ]]


In [33]:
#- Find Transpose of M3, Call it MT1. Check if M3 == MT1
import numpy as np
m1=np.linspace(1,17,16).reshape(4,4)
m2=m1.T
m3=m1+m2
mt1=m3.T
print(mt1)
print(m3==mt1)

[[ 2.          7.33333333 12.66666667 18.        ]
 [ 7.33333333 12.66666667 18.         23.33333333]
 [12.66666667 18.         23.33333333 28.66666667]
 [18.         23.33333333 28.66666667 34.        ]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [75]:
#- find diffrence of M4 = (M1 - M2)
import numpy as np
m1=np.linspace(1,17,16).reshape(4,4)
m2=m1.T
m4=m1-m2
print(m1)
print(m2)
print(m4)

[[ 1.          2.06666667  3.13333333  4.2       ]
 [ 5.26666667  6.33333333  7.4         8.46666667]
 [ 9.53333333 10.6        11.66666667 12.73333333]
 [13.8        14.86666667 15.93333333 17.        ]]
[[ 1.          5.26666667  9.53333333 13.8       ]
 [ 2.06666667  6.33333333 10.6        14.86666667]
 [ 3.13333333  7.4        11.66666667 15.93333333]
 [ 4.2         8.46666667 12.73333333 17.        ]]
[[ 0.  -3.2 -6.4 -9.6]
 [ 3.2  0.  -3.2 -6.4]
 [ 6.4  3.2  0.  -3.2]
 [ 9.6  6.4  3.2  0. ]]


In [35]:
#- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

import numpy as np
m1=np.linspace(1,17,16).reshape(4,4)
m2=m1.T
m4=m1-m2
mt2=m4.T
print(mt2)
print(m4==mt2)
print(m4==(-1*mt2))

[[ 0.   3.2  6.4  9.6]
 [-3.2  0.   3.2  6.4]
 [-6.4 -3.2  0.   3.2]
 [-9.6 -6.4 -3.2  0. ]]
[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [37]:
#- create a matrix (3x4) R1 of random numbers between 10-40

import numpy as np
r1=np.random.randint(10,40,12)
print(r1.reshape(3,4))

[[24 38 36 14]
 [24 24 18 21]
 [27 30 36 31]]


In [39]:
#- find min and max column wise

import numpy as np
r1=np.random.randint(10,40,12).reshape(3,4)
print(r1)
print(r1.min(axis=0))
print(r1.max(axis=0))

[[29 24 22 14]
 [29 27 27 31]
 [35 37 12 37]]
[29 24 12 14]
[35 37 27 37]


In [46]:
#- replace the last column with sum of all the columns
import numpy as np
r1=np.random.randint(10,40,12).reshape(3,4)
print(r1)
print(r1[:,3])
print(r1.sum(axis=1))
r1[:,3]=r1.sum(axis=1)
print(r1)

[[18 15 37 14]
 [11 28 32 25]
 [16 16 39 33]]
[14 25 33]
[ 84  96 104]
[[ 18  15  37  84]
 [ 11  28  32  96]
 [ 16  16  39 104]]


In [73]:
# - create a matrix (3x4) R1 of random numbers between 10-40
# - replace all even elements with nan in R1
# - count number of nan in R1

import numpy as np
r1=np.random.randint(10,40,12).reshape(3,4)
res=np.array(r1,dtype='float64') #nan is float type.
print(res)
i=res%2==0
res[i]=np.nan           #replaced even numbers with nan.
print(res)
n=np.isnan(res)         #check for nan values in the ndarray.
print(n.sum())          #count of nan values.

[[32. 37. 38. 13.]
 [21. 26. 39. 15.]
 [26. 28. 21. 32.]]
[[nan 37. nan 13.]
 [21. nan 39. 15.]
 [nan nan 21. nan]]
6


In [50]:
import numpy as np
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
