## NUMPY
- create a numpy array of 5 zeros.
- check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative

  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [19]:
#1.create a numpy array of 5 zeros.check datatype, itemsize and shape of above
import numpy as np
a = np.zeros(5)
print(a,a.dtype,a.shape,a.itemsize)

[0. 0. 0. 0. 0.] float64 (5,) 8


In [1]:
# 2.create a numpy array of ones of shape (5,4)
import numpy as np
a = np.ones((5,4) ,dtype='int32')
print(a,a.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] (5, 4)


In [35]:
# 3. create a matrix of shape 4,5 with numbers from 1-20
import numpy as np
a = np.arange(1,21)
r= a.reshape(4,5)
print(r)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [36]:
# 4. multiply all elements of above array by 10
import numpy as np
a = np.arange(1,21)
r= a.reshape(4,5)
print(r)
print()
print(a*10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200]


In [40]:
# 5. print odd elements from array
import numpy as np
a = np.arange(1,21)
r= a.reshape(4,5)
print(r)
print()
print(a[np.where(a%2!=0)])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[ 1  3  5  7  9 11 13 15 17 19]


In [2]:
# 6.Replace all even elements by their negative
import numpy as np
a = np.arange(1,21)
r= a.reshape(4,5)
a[np.where(a%2==0)] = -a[np.where(a%2==0)]
print(r)

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [6]:
#7.create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
import numpy as np
M1= np.linspace(1,16,16)
M1.resize(4,4)
print(M1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [67]:
# 8.Create a transpose of above matrix call it M2
import numpy as np
M1= np.linspace(1,16,16)
M1.resize(4,4)
M2=np.transpose(M1)
print(M2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [68]:
#9.Find sum of above matrix M3 = (M1 + M2)
import numpy as np
M1= np.linspace(1,16,16)
M1.resize(4,4)
M2=np.transpose(M1)
M3=(M1+M2)
print(M3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [69]:
#10.Find Transpose of M3, Call it MT1. Check if M3 == MT1
import numpy as np
M1= np.linspace(1,16,16)
M1.resize(4,4)
M2=np.transpose(M1)
M3=(M1+M2)
MT1=np.transpose(M3)
print((M3==MT1).all())

True


In [70]:
#11.Find diffrence of M4 = (M1 - M2)
import numpy as np
M1= np.linspace(1,16,16)
M1.resize(4,4)
M2=np.transpose(M1)
M3=(M1+M2)
M4=(M1-M2)
print(M4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [71]:
#12.Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
import numpy as np
M1= np.linspace(1,16,16)
M1.resize(4,4)
M2=np.transpose(M1)
M3=(M1+M2)
M4=(M1-M2)
MT2 = np.transpose(M4)
print((M4==MT2).all())
print((M4==-MT2).all())

False
True


In [78]:
#13.Create a matrix (3x4) R1 of random numbers between 10-40 find min and max column wise

import numpy as np
R1 = np.random.randint(10,40,12)
R1.resize(3,4)
R1 = np.matrix(R1)
print(R1)
print()

print("min", np.min(R1, axis=0))
print("max", np.max(R1, axis=0))

[[22 19 18 34]
 [33 38 22 17]
 [34 21 30 20]]

min [[22 19 18 17]]
max [[34 38 30 34]]


In [77]:
#14. replace the last column with sum of all the columns
R1[:,3] = np.sum(R1, axis=1)
print(R1)

[[ 10  17  13 117]
 [ 32  12  32 188]
 [ 29  10  30 161]]


In [7]:
# create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,(3,4))
print(R1)

[[29 37 10 32]
 [18 20 23 12]
 [26 25 17 19]]


In [14]:
# replace all even elements with nan in R1

R1 = R1.astype('float')
R1[R1 % 2==0] = np.nan
print(R1)

[[nan nan 21. 21.]
 [nan 33. 13. nan]
 [35. 21. nan nan]]


In [12]:

# count number of nan in R1

print(np.count_nonzero(np.isnan(R1)))

6


In [15]:
# 15.check output of this code
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
