## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [5]:
#Q1 create a numpy array of 5 zeros. check datatype, itemsize and shape of above
import numpy as np
a=np.zeros(5)
print(a, a.dtype, a.itemsize, a.shape)

[0. 0. 0. 0. 0.] float64 8 (5,)


In [9]:
#Q2 create a numpy array of ones of shape (5,4)
print(np.ones((5,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [130]:
#Q3 create a matrix of shape 4,5 with numbers from 1-20
m=np.arange(1,21).reshape(4,5)
print(m)
print(m.shape)
print()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)



In [131]:
#Q4. multiply all elements of above array by 10

mul=m*10
print(mul)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [144]:
#Q5. print odd elements from array

odd=m%2!=0
print(m[odd])

#Q6. replace all even elements by their negative


print()
m[m%2==0]*=-1
print(m)

    


[ 1  3  5  7  9 11 13 15 17 19]

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [164]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
# create a transpose of above matrix call it M2
# find sum of above matrix M3 = (M1 + M2)
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
# find diffrence of M4 = (M1 - M2)
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

M1=np.arange(1,17).reshape(4,4)
print(M1)

M2=M1.T
print()
print(M2)

print()
M3=M1+M2
print(M3)

print()
MT1=M3.T
print(MT1)

print()
M4 = (M1 - M2)
print(M4)
print()

MT2=(M4.T)*(-1)
print(MT2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [126]:
# create a matrix (3x4) R1 of random numbers between 10-40
# find min and max column wise
# replace the last column with sum of all the columns

import numpy as np
R1=np.random.randint(10,40, size=(3,4))
print(R1)

print()
print("min: ",R1.min(axis=0))
print("max: ",R1.max(axis=0))

for i in range(0,3):
    R1[i,3]=R1[:,i].sum(axis=0)
    print()
print(R1)



[[22 19 23 33]
 [26 18 35 30]
 [24 36 36 16]]

min:  [22 18 23 16]
max:  [26 36 36 33]



[[22 19 23 72]
 [26 18 35 73]
 [24 36 36 94]]


In [108]:
# create a matrix (3x4) R1 of random numbers between 10-40
# replace all even elements with nan in R1
# count number of nan in R1

import numpy as np
from numpy import nan

R1=np.random.randint(10,40, size=(3,4))
print(R1)

R1[R1%2==0]=nan
print(R1)


R2=R1==9
print(R2.sum())

[[27 10 35 18]
 [38 14 36 25]
 [24 19 23 39]]


ValueError: cannot convert float NaN to integer

In [50]:
# check output of this code
a1 = np.arange(1,10).reshape(3,3)
print(a1)

a2 = np.arange(11,20).reshape(3,3)
print()
print(a2)

a3 = np.append(a1,a2)
print()
print(a3, a3.shape)

a3 = np.append(a1,a2, axis = 0)
print()
print(a3, a3.shape)

a3 = np.append(a1,a2, axis = 1)
print(a3,a3.shape)



[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19] (18,)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]] (6, 3)
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]] (3, 6)
