## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [9]:
import numpy as np

print(np.zeros(5))
print(np.size)
print(np.shape)
print(np.dtype)

[0. 0. 0. 0. 0.]
<function size at 0x0000022557E78048>
<function shape at 0x0000022557E6E048>
<class 'numpy.dtype'>


In [13]:
#create a numpy array of ones of shape (5,4)
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
#create a matrix of shape 4,5 with numbers from 1-20
a=np.arange(1,21)
b=a.reshape(4,5)
print(b)
#multiply all elements of above array by 10
c=b*10
print(c)
#print odd elements from array
d=(b%2!=0)
print(b[d])

print(c[d])
#replace all even elements by their negative

e=(b%2==0)

print(b[e]*-1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]
[ 1  3  5  7  9 11 13 15 17 19]
[ 10  30  50  70  90 110 130 150 170 190]
[ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]


In [37]:
#create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

M0=a=np.arange(1,17)
M1=a.reshape(4,4)
print("M1",M1)
#create a transpose of above matrix call it M2
M2=M1.T
print("M2",M2)
#find sum of above matrix M3 = (M1 + M2)
M3 =M1+M2
print("M3",M3)
#Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1=M3.T
if (M3.all()==MT1.all()):
    print(True)
else:
    print(False)

#find diffrence of M4 = (M1 - M2)
M4 = M1-M2
print("M4",M4)
#Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 =M4.T
if (M4.all()==~MT2.all()):
    print(True)
else:
    print(False)


M1 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
M2 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
M3 [[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]
True
M4 [[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]
False


In [38]:
#create a matrix (3x4) R1 of random numbers between 10-40
import numpy as np
R1=np.random.randint(10,40, size=(3,4))
print(R1)
#find min and max column wise

print("minmum",R1.min(axis=0))
print("maximum ",R1.max(axis=0))

#replace the last column with sum of all the columns

[[20 27 34 11]
 [34 26 12 25]
 [25 32 30 38]]
minmum [20 26 12 11]
maximum  [34 32 34 38]


In [40]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
