## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [31]:
# create a numpy array of 5 zeros.
# check datatype, itemsize and shape of above
print("Q1.create a numpy array of 5 zeros.check datatype, itemsize and shape of above")
import numpy as np
a = np.zeros(5)
print(a)
print(a.dtype)
print(a.shape)
print(a.itemsize)
print(a.size)

print("********"*10)
print("\n")
print("Q2.create a numpy array of ones of shape (5,4)")
# create a numpy array of ones of shape (5,4)
b = np.ones((5,4))
print(b)

print("********"*10)
print("\n")
print("Q3.create a matrix of shape 4,5 with numbers from 1-20")
# create a matrix of shape 4,5 with numbers from 1-20

c = np.arange(1,21)
print(c)
d = c.reshape(4,5)
print(d, d.shape)

print("********"*10)
print("\n")
print("Q4.multiply all elements of above array by 10")
# multiply all elements of above array by 10
print(d*10)
print("********"*10)
print("\n")
print("Q5.print odd elements from array")
# print odd elements from array
r=(d%2!=0)
print(d[r])

print("********"*10)
print("\n")
print("Q6.replace all even elements by their negative")
# replace all even elements by their negative
print(d*(-1))

Q1.create a numpy array of 5 zeros.check datatype, itemsize and shape of above
[0. 0. 0. 0. 0.]
float64
(5,)
8
5
********************************************************************************


Q2.create a numpy array of ones of shape (5,4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
********************************************************************************


Q3.create a matrix of shape 4,5 with numbers from 1-20
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] (4, 5)
********************************************************************************


Q4.multiply all elements of above array by 10
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]
********************************************************************************


Q5.print odd elements from array
[ 1  3  5  7  9 11 13 15 17 19]
*******************************

In [67]:

print("********"*10)
print("\n")
print("Q1.create a linearly spaced matrix M1 of size 4x4 having values in range 1-16")
M1= np.arange(1,17).reshape(4,4)
print(M1)

print("********"*10)
print("\n")
print("Q2.create a transpose of above matrix call it M2")
M2=M1.transpose()
print(M2)

print("********"*10)
print("\n")
print("Q3.find sum of above matrix M3 = (M1 + M2")

M3=M1+M2
print(M3)

print("********"*10)
print("\n")
print("Q4.Find Transpose of M3, Call it MT1. Check if M3 == MT1")
MT1=M3.transpose()

if (M3==MT1).all()==True:
    print("M3,MT1 are matching")
else:
    print("M3,MT1 are not matching")
# count=0
# for i in range(M3.itemsize):
#     for j in range(MT1.itemsize):
#         if M3[i][j]==MT1[i][j]:
#             count+=1

# if count==MT1.size:
#     print("It's a match")
# else:
#     print("Not matching")


print("********"*10)
print("\n")
print("Q5.# find diffrence of M4 = (M1 - M2)")

M4=M1-M2
print(M4)

print("********"*10)
print("\n")
print("Q6.# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2")

MT2=M4.transpose()
print('MT2\n',MT2)

#Method1
if (M4==MT2).all()==True:
    print("M4,MT2 are matching")
else:
    print("M4,MT2 are not matching")
    
#Method2
if np.array_equal(M4,MT2)==True:
    print("M4,MT2 are matching")
else:
    print("M4,MT2 are not matching")

if np.array_equal(M4,-MT2)==True:
    print("M4 is negation of MT2")
else:
    print("M4 is Not negation of MT2")



********************************************************************************


Q1.create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
********************************************************************************


Q2.create a transpose of above matrix call it M2
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
********************************************************************************


Q3.find sum of above matrix M3 = (M1 + M2
[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]
********************************************************************************


Q4.Find Transpose of M3, Call it MT1. Check if M3 == MT1
M3,MT1 are matching
********************************************************************************


Q5.# find diffrence of M4 = (M1 - M2)
[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]
*********************************************************

In [111]:

print("********"*10)
print("\n")
print("Q1.create a matrix (3x4) R1 of random numbers between 10-40")

R1=np.random.randint(10, 40,12).reshape(3,4)
print(R1)

print("********"*10)
print("\n")
print("Q2.# find min and max column wise")

print("Minimum is",R1.min(axis=0),"Maximum is",R1.max(axis=0))


print("********"*10)
print("\n")
print("Q3.# replace the last column with sum of all the columns")

print(R1.sum(axis=0))
# print(len(R1),R1.shape)
(x,y)=R1.shape
# print("Output",x,y)
sum=0
for j in range(y):
    for i in range(x):
        if i==(x-1):
            R1[i][j]=sum+R1[i][j]
            sum=0
        else:
            sum+=R1[i][j]
            
print('New result \n',R1)

            
    
    

********************************************************************************


Q1.create a matrix (3x4) R1 of random numbers between 10-40
[[14 31 38 16]
 [31 10 23 30]
 [29 28 17 32]]
********************************************************************************


Q2.# find min and max column wise
Minimum is [14 10 17 16] Maximum is [31 31 38 32]
********************************************************************************


Q3.# replace the last column with sum of all the columns
[74 69 78 78]
New result 
 [[14 31 38 16]
 [31 10 23 30]
 [74 69 78 78]]


In [112]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
