## NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [10]:
import numpy as np
n=np.zeros(5)
print(n)
print(n.dtype)
print(n.itemsize)
print(n.shape)


[0. 0. 0. 0. 0.]
float64
8
(5,)


In [15]:
n=np.ones(20).reshape(5,4)
print(n)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
n=np.arange(20).reshape(5,4)
print(n)
y=n*10
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]
 [120 130 140 150]
 [160 170 180 190]]


In [27]:
print((n[n%2!=0]))

[ 1  3  5  7  9 11 13 15 17 19]


In [29]:
print((n[n%2==0])*-1)

[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18]


In [31]:
m1=np.arange(16).reshape(4,4)
print(m1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [32]:
m2 = np.transpose(m1)
print(m2)

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [33]:
m3=m1+m2
print(m3)

[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]


In [34]:
mt1=np.transpose(m3)
print(mt1==m3)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [36]:
m4=(m1-m2)
print(m4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [42]:
mt2=np.transpose(m4)
print(mt2==m4)
print()
print((-(mt2)==m4))

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [114]:
R1=np.random.randint(10,40,12).reshape(3,4)
print(R1)

print(np.amin(R1,axis=0))
print(np.amax(R1,axis=0))
R1[:,3]=np.sum(R1,axis=1)
print(R1)

[[21 38 15 25]
 [10 29 34 33]
 [36 19 29 17]]
[10 19 15 17]
[36 38 34 33]
[[ 21  38  15  99]
 [ 10  29  34 106]
 [ 36  19  29 101]]


In [134]:
r1=np.random.randint(10,40,12).reshape(3,4)
print (r1)
r1 = r1.astype(float)
r1[r1%2==0]=np.nan

print(r1)
print()
print(np.count_nonzero(np.isnan(r1)))

[[13 27 24 29]
 [33 23 22 18]
 [30 16 15 11]]
[[13. 27. nan 29.]
 [33. 23. nan nan]
 [nan nan 15. 11.]]

5


In [135]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
