In [2]:
import numpy as np

In [12]:
# create a numpy array of 5 zeros.
npzero = np.array([0]*5)
print(npzero)

#  - check datatype, itemsize and shape of above
print(type(npzero), npzero.itemsize, npzero.shape )

[0 0 0 0 0]
<class 'numpy.ndarray'> 4 (5,)


In [15]:
# create a numpy array of ones of shape (5,4)

x = np.array([[1,2,3,4,5],[4,5,6,7,8], [8,9,9,8,7], [7,6,5,4,4]]).reshape(5,4)
print(x)

[[1 2 3 4]
 [5 4 5 6]
 [7 8 8 9]
 [9 8 7 7]
 [6 5 4 4]]


In [19]:
# create a matrix of shape 4,5 with numbers from 1-20

x = np.arange(1,21).reshape(4,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
# multiply all elements of above array by 10
print(x*10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [35]:
# print odd elements from array
# y = x % 2 != 0
print(x[x % 2 != 0])

[ 1  3  5  7  9 11 13 15 17 19]


In [43]:
# replace all even elements by their negative
print(-x[x % 2 == 0])

[ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]


In [46]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
M1 = np.arange(1,17).reshape(4,4)
print(M1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [48]:
# create a transpose of above matrix call it M2
M2 = M1.transpose()
print(M2)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [51]:
# find sum of above matrix M3 = (M1 + M2)
M3 = (M1+M2)
print(M3)

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]


In [58]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
MT1 = M3.transpose()
print(MT1)
print((M3 == MT1).all())
print(np.equal(M3, MT1).all())

[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]
True
True


In [60]:
# find diffrence of M4 = (M1 - M2)
M4 = M1-M2
print(M4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [62]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
MT2 = M4.transpose()
print(MT2)
print((M4 == -MT2).all())

[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]
True


In [112]:
# create a matrix (3x4) R1 of random numbers between 10-40

R1 = np.random.randint(10,40,size=(3,4))
print(R1)

[[19 21 13 22]
 [39 18 36 38]
 [28 15 16 11]]


In [113]:
# find min and max column wise
print("min value: ", R1.min(axis = 0))
print("max value: ", R1.max(axis = 0))

min value:  [19 15 13 11]
max value:  [39 21 36 38]


In [116]:
# - replace the last column with sum of all the columns
z = R1.sum()
print(z)
R1[:, 3] =  z
print(R1)

3304
[[  19   21   13 3304]
 [  39   18   36 3304]
 [  28   15   16 3304]]


In [217]:
# create a matrix (3x4) R1 of random numbers between 10-40
R1 = np.random.randint(10,40,size=(3,4))
R1 = R1.astype("float")
print(R1)

[[34. 15. 16. 19.]
 [36. 34. 11. 32.]
 [21. 37. 21. 38.]]


In [218]:
# replace all even elements with nan in R1

print("Original Value: ")
print(R1)

R1[R1 % 2 == 0] = np.nan
print("replace all even elements with nan in R1: ")
print(R1)


Original Value: 
[[34. 15. 16. 19.]
 [36. 34. 11. 32.]
 [21. 37. 21. 38.]]
replace all even elements with nan in R1: 
[[nan 15. nan 19.]
 [nan nan 11. nan]
 [21. 37. 21. nan]]


In [219]:
# count number of nan in R1

print(np.count_nonzero(np.isnan(R1)))

6


In [173]:
# check output of this code  
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
