In [74]:
NUMPY
create a numpy array of 5 zeros.
check datatype, itemsize and shape of above
create a numpy array of ones of shape (5,4)
create a matrix of shape 4,5 with numbers from 1-20
multiply all elements of above array by 10
print odd elements from array
replace all even elements by their negative
create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
create a transpose of above matrix call it M2
find sum of above matrix M3 = (M1 + M2)
Find Transpose of M3, Call it MT1. Check if M3 == MT1
find diffrence of M4 = (M1 - M2)
Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
create a matrix (3x4) R1 of random numbers between 10-40
find min and max column wise
replace the last column with sum of all the columns
create a matrix (3x4) R1 of random numbers between 10-40
replace all even elements with nan in R1
count number of nan in R1
check output of this code
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

In [3]:
# create a numpy array of 5 zeros.
# check datatype, itemsize and shape of above

import numpy as np
array = np.zeros(5)                    # defining array with datatype
array1 = np.zeros(5, dtype='int32')

print(type(array))
print(type(array1))                   #type of array

print(type(array[0]))
print(type(array1[0]))                #data type of array

print(array.itemsize)            
print(array1.itemsize)                #itemsize of array

print(array.shape)
print(array1.shape)                   #shape of array

# create a numpy array of ones of shape (5,4)

import numpy as np
array = np.ones((5,4))
print(array)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.int32'>
8
4
(5,)
(5,)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# create a matrix of shape 4,5 with numbers from 1-20
# multiply all elements of above array by 10
# print odd elements from array
# replace all even elements by their negative

import numpy as np
matrix = np.arange(1,21).reshape(4,5)
print(matrix)                               #matrix of 20 numbers

print()
print(matrix * 10)                          #multiplied by 10

print()
odd = matrix % 3==0
r=matrix[odd]                               #odd elements from array
print(r)

print()
even = matrix % 2==0       
r=matrix[even]                 
print(r)                                    #replaced even elements by negatives
print(r*-1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]

[ 3  6  9 12 15 18]

[ 2  4  6  8 10 12 14 16 18 20]
[ -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]


In [5]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
# create a transpose of above matrix call it M2
# find sum of above matrix M3 = (M1 + M2)
# Find Transpose of M3, Call it MT1. Check if M3 == MT1
# find diffrence of M4 = (M1 - M2)
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

M1 = np.arange(1,17).reshape(4,4)
print(M1)                                                                    #matrix of 16 numbers

print("\n Transpose of matrix M1: ")
M2 = M1.T                                                                   #transpose matrix
print(M2)

print("\n sum of M1 and M2: ")                         
M3 = M1 + M2                                                                #sum of m1 and m2
print(M3)

print("\n Transpose of M3: ")
MT1 = M3.T                                                                 #transpose of m3
print(MT1)

print("\n Checking if MT1 == M3\n",MT1 == M3)                              #Checking if MT1 == M3

print("\n Difference of M1 and M2: ")
M4 = M1 - M2                                                               #difference of m1 and m2
print(M4)

print("\n Transpose of M4: ")
MT2 = M4.T                                                                 #transpose of m4
print(MT2)

print("\n Checking if MT2 == M4\n",MT2 == M4)                              #Checking if MT2 == M4

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

 Transpose of matrix M1: 
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

 sum of M1 and M2: 
[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

 Transpose of M3: 
[[ 2  7 12 17]
 [ 7 12 17 22]
 [12 17 22 27]
 [17 22 27 32]]

 Checking if MT1 == M3
 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

 Difference of M1 and M2: 
[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]

 Transpose of M4: 
[[ 0  3  6  9]
 [-3  0  3  6]
 [-6 -3  0  3]
 [-9 -6 -3  0]]

 Checking if MT2 == M4
 [[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


In [57]:
# create a matrix (3x4) R1 of random numbers between 10-40
# find min and max column wise
# replace the last column with sum of all the columns

R1 = np.random.randint(low=10, high=40, size=(12)).reshape(3,4)     
print(R1)                                                                    #random matrix numbers b/w 10-40

print("\n Min elements from each column: ")                                  #minimum elements from each column
print(R1.min(axis = 1)) 

print("\n Sum of all the columns: ")
R1sum= R1.sum(axis =1) 
print(R1sum)                                                                 #sum of all column elements

print("\n Replacing last column with R1sum: ")                               #replace of last column
R1[:,3] = R1sum 
print(R1)

[[22 15 26 26]
 [13 36 23 13]
 [22 15 23 38]]

 Min elements from each column: 
[15 13 15]

 Sum of all the columns: 
[89 85 98]

 Replacing last column with R1sum: 
[[22 15 26 89]
 [13 36 23 85]
 [22 15 23 98]]


In [68]:
# create a matrix (3x4) R1 of random numbers between 10-40
# replace all even elements with nan in R1
# count number of nan in R1

R1 = np.random.randint(low=10, high=40, size=(12)).reshape(3,4)                         #random matrix numbers b/w 10-40  
print(R1)

print()
R1 = R1.astype('float')
R1[R1 % 2==0] = np.nan                                                                 #Replaced all even numbers with nan
print("\nReplaced all even numbers with nan\n",R1)


print("\n Number of Nan in numpy array\n",np.count_nonzero(np.isnan(R1)))             #count of nan in R1

[[26 32 26 26]
 [31 23 35 17]
 [23 34 30 19]]


Replaced all even numbers with nan
 [[nan nan nan nan]
 [31. 23. 35. 17.]
 [23. nan nan 19.]]

 Number of Nan in numpy array
 6


In [73]:
# check output of this code
# a1 = np.arange(1,10).reshape(3,3)
# a2 = np.arange(11,20).reshape(3,3)
# a3 = np.append(a1,a2)
# print(a3)
# a3 = np.append(a1,a2, axis = 0)
# print(a3)
# a3 = np.append(a1,a2, axis = 1)
# print(a3)

a1 = np.arange(1,10).reshape(3,3)
print(a1)

print()
a2 = np.arange(11,20).reshape(3,3)
print(a2)

print()
a3 = np.append(a1,a2, axis = 0)
print(a3)

print()
a3 = np.append(a1,a2, axis = 1)
print(a3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
