# NUMPY
- create a numpy array of 5 zeros.
    - check datatype, itemsize and shape of above
- create a numpy array of ones of shape (5,4)
- create a matrix of shape 4,5 with numbers from 1-20
- multiply all elements of above array by 10
- print odd elements from array
- replace all even elements by their negative
  
  
  
- create a linearly spaced matrix M1 of size 4x4 having values in range 1-16
- create a transpose of above matrix call it M2
- find sum of above matrix M3 = (M1 + M2)
- Find Transpose of M3, Call it MT1. Check if M3 == MT1
- find diffrence of M4 = (M1 - M2)
- Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2
  

- create a matrix (3x4) R1 of random numbers between 10-40
- find min and max column wise
- replace the last column with sum of all the columns


- create a matrix (3x4) R1 of random numbers between 10-40
- replace all even elements with nan in R1
- count number of nan in R1



- check output of this code  
`a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)
`


In [2]:
# create a numpy array of 5 zeros and check datatype, itemsize and shape of above.

import numpy as np

array1 = np.zeros(5)
print(array1)
print(array1.dtype)
print(array1.itemsize)
print(array1.shape)

[0. 0. 0. 0. 0.]
float64
8
(5,)


In [3]:
# create a numpy array of ones of shape (5,4).

array2 = np.ones((5,4))
print(array2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# create a matrix of shape 4,5 with numbers from 1-20.

array3 = np.arange(1,21)
modified_array3 = array3.reshape(4,5)
print(modified_array3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
# multiply all elements of above array by 10.

print(modified_array3 * 10)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]]


In [6]:
# print odd elements from array.

array4 = np.arange(-10, 10).reshape(4,5)
print(array4)

odd_elements = array4 % 2 != 0

print()
array5 = array4[odd_elements]
print(array5)

[[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]
 [  5   6   7   8   9]]

[-9 -7 -5 -3 -1  1  3  5  7  9]


In [7]:
# replace all even elements by their negative.

array6 = np.arange(1,21).reshape(4,5)
array6[np.where(array6 % 2 == 0)] = -array6[np.where(array6 % 2 ==0)]
print(array6)

[[  1  -2   3  -4   5]
 [ -6   7  -8   9 -10]
 [ 11 -12  13 -14  15]
 [-16  17 -18  19 -20]]


In [8]:
# create a linearly spaced matrix M1 of size 4x4 having values in range 1-16.

M1 = np.linspace(1,16,16)
M1.resize(4,4)
print(M1)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [11]:
# create a transpose of above matrix call it M2.

M1 = np.linspace(1,16,16)
M1.resize(4,4)
M2 = M1.transpose()
print(M2)

[[ 1.  5.  9. 13.]
 [ 2.  6. 10. 14.]
 [ 3.  7. 11. 15.]
 [ 4.  8. 12. 16.]]


In [12]:
# find sum of above matrix M3 = (M1 + M2).

M1 = np.linspace(1,16,16)
M1.resize(4,4)
M2 = M1.transpose()
M3 = M1 + M2
print(M3)

[[ 2.  7. 12. 17.]
 [ 7. 12. 17. 22.]
 [12. 17. 22. 27.]
 [17. 22. 27. 32.]]


In [19]:
# Find Transpose of M3, Call it MT1. Check if M3 == MT1.

M1 = np.linspace(1,16,16)
M1.resize(4,4)
M2 = M1.transpose()
M3 = M1 + M2
MT1 = M3.transpose()

print()
if M3.all() == MT1.all():
    print('Yes')
else:
    print('No')


Yes


In [20]:
# find diffrence of M4 = (M1 - M2).

M1 = np.linspace(1,16,16)
M1.resize(4,4)
M2 = M1.transpose()
M4 = M1 - M2
print(M4)

[[ 0. -3. -6. -9.]
 [ 3.  0. -3. -6.]
 [ 6.  3.  0. -3.]
 [ 9.  6.  3.  0.]]


In [23]:
# Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2.

M1 = np.linspace(1,16,16)
M1.resize(4,4)
M2 = M1.transpose()
M4 = M1 - M2
MT2 = M4.transpose()

print((M4 == MT2).all())
print((M4 == -MT2).all())

False
True


In [35]:
# create a matrix (3x4) R1 of random numbers between 10-40 and find min and max column wise

R1 = np.random.randint(10,41,20)
R1.resize(3,4)
print(R1)

print()
print('min' , np.min(R1, axis=0))
print('max' , np.max(R1, axis=0))

[[35 13 21 20]
 [13 34 27 34]
 [35 27 24 14]]

min [13 13 21 14]
max [35 34 27 34]


In [38]:
# replace the last column with sum of all the columns.

R1[:,3] = np.sum(R1, axis = 1)
print(R1)

[[ 35  13  21 158]
 [ 13  34  27 182]
 [ 35  27  24 186]]


In [8]:
# create a matrix (3x4) R1 of random numbers between 10-40.

import numpy as np
R1 = np.random.randint(10,41,(3,4))
print(R1)
print(R1.dtype)

[[28 16 22 34]
 [37 19 16 40]
 [24 12 26 25]]
int32


In [10]:
# replace all even elements with nan in R1.

R1 = R1.astype('float')
R1[R1 % 2==0] = np.nan
print(R1)

[[nan nan nan nan]
 [37. 19. nan nan]
 [nan nan nan 25.]]


In [11]:
# count number of nan in R1.

print(np.count_nonzero(np.isnan(R1)))

9


In [10]:
# check output of this code  
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
