In [7]:
#create a numpy array of 5 zeros.

import numpy as np
np_array = np.array([0,0,0,0,0])
print(type(np_array))
print(np_array.dtype)
print(np_array.itemsize)
print(np_array.shape)

<class 'numpy.ndarray'>
int32
4
(5,)


In [11]:
#create a numpy array of ones of shape (5,4)

import numpy as np
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
print(x)
print(x.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
(5, 4)


In [13]:
#create a matrix of shape 4,5 with numbers from 1-20

import numpy as np
x_1 = np.array([[1,2,3,4,17],[5,6,7,8,18],[9,10,11,12,19],[13,14,15,16,20]])
print(x_1)
print(x_1.shape)

[[ 10  20  30  40 170]
 [ 50  60  70  80 180]
 [ 90 100 110 120 190]
 [130 140 150 160 200]]
(4, 5)


In [15]:
#multiply all elements of above array by 10

import numpy as np
x_1 = np.array([[1,2,3,4,17],[5,6,7,8,18],[9,10,11,12,19],[13,14,15,16,20]])
y = x_1*10
print(y)
print(y.shape)

[[ 10  20  30  40 170]
 [ 50  60  70  80 180]
 [ 90 100 110 120 190]
 [130 140 150 160 200]]
(4, 5)


In [17]:
#print odd elements from array

import numpy as np
x_1 = np.array([[1,2,3,4,17],[5,6,7,8,18],[9,10,11,12,19],[13,14,15,16,20]])
y = x_1*10
for data in y:
    print(data)
    import time
    time.sleep(2)

[ 10  20  30  40 170]
[ 50  60  70  80 180]
[ 90 100 110 120 190]
[130 140 150 160 200]


In [42]:
##replace all even elements by their negative

import numpy as np
a = np.array([[1,2,3,4,17],[5,6,7,8,18],[9,10,11,12,19],[13,14,15,16,20]])
y = a%2 == 0
print(a[y]*-1)

[ -2  -4  -6  -8 -18 -10 -12 -14 -16 -20]


In [45]:
#create a linearly spaced matrix M1 of size 4x4 having values in range 1-16

M1 = np.arange(0,16).reshape(4,4)
print(M1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [46]:
#create a transpose of above matrix call it M2

M2 = np.transpose(M1)
print(M2)

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [47]:
#find sum of above matrix M3 = (M1 + M2)

M3 = M1 + M2
print(M3)

[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]


In [57]:
#Find Transpose of M3, Call it MT1. Check if M3 == MT1

MT1 = np.transpose(M3)
print(MT1)
print(M3 == MT1)

[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [51]:
#find diffrence of M4 = (M1 - M2)

M4 = M1 - M2
print(M4)

[[ 0 -3 -6 -9]
 [ 3  0 -3 -6]
 [ 6  3  0 -3]
 [ 9  6  3  0]]


In [58]:
#Find Transpose of M4, Call it MT2. Check if M4 == MT2. Also check if M4 == -MT2

MT2 = np.transpose(M4)
print(M4 == MT2)
print(M4 == -MT2)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [66]:
#create a matrix (3x4) R1 of random numbers between 10-40

a = np.random.randint(10,40,size=(3,4))
print(a)

[[24 28 27 34]
 [25 37 30 24]
 [26 27 35 33]]


In [69]:
#find min and max column wise

a = np.random.randint(10,40,size=(3,4))
print(a)
print("Min. Column",a.min(axis=0))
print("Max. Column",a.max(axis=0))
print("Min. Row",a.min(axis=1))
print("Max. Row",a.max(axis=1))

[[26 13 30 29]
 [13 25 15 31]
 [19 10 25 20]]
Min. Column [13 10 15 20]
Max. Column [26 25 30 31]
Min. Row [13 13 10]
Max. Row [30 31 25]


In [81]:
#replace the last column with sum of all the columns

a = np.random.randint(low = 10,high = 40,size=(3,4))
print(a)
sum_data = np.sum(a, axis = 1)
print("---------")
print(sum_data)
a[:,3] = sum_data
print("---------")
print(a)

[[10 22 21 25]
 [20 21 12 38]
 [32 11 15 31]]
---------
[78 91 89]
---------
[[10 22 21 78]
 [20 21 12 91]
 [32 11 15 89]]


In [82]:
#create a matrix (3x4) R1 of random numbers between 10-40

R1 = np.random.randint(low = 10,high = 40,size=(3,4))
print(R1)

[[34 26 34 36]
 [24 34 18 21]
 [31 12 26 28]]


In [92]:
#replace all even elements with nan in R1

R1 = np.random.randint(low = 10,high = 40,size=(3,4))
R1 = R1.astype("float")
print(R1)
even_num = R1%2 == 0
print(even_num)
R1[even_num] = np.nan
print("--------------------------------")
print(R1)

[[37. 30. 27. 21.]
 [15. 19. 18. 15.]
 [15. 14. 38. 20.]]
[[False  True False False]
 [False False  True False]
 [False  True  True  True]]
--------------------------------
[[37. nan 27. 21.]
 [15. 19. nan 15.]
 [15. nan nan nan]]


In [93]:
#count number of nan in R1

print(np.count_nonzero(np.isnan(R1)))

5


In [94]:
#check output of this code

a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
a3 = np.append(a1,a2)
print(a3)
a3 = np.append(a1,a2, axis = 0)
print(a3)
a3 = np.append(a1,a2, axis = 1)
print(a3)

[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
